# This is a basic workflow that is manually triggered

name: Manual workflow



# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '*/2 * * * *' # every 30 minutes
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          # owner: llvm
          base: master
          head: master
